### PR TITLE
[llvm] Make sure that BenchmarkFactory::close() is called

### LINKED ISSUE #582: Is running CompilerGym intended to leave cache directories behind?
## ❓ Questions and Help

Not sure if this is a bug or not, so submitting as a question. Running a CompilerGym experiment leaves behind many cache directories. When running a large experiment, this can create problems through the sheer number of directories in `COMPILER_GYM_CACHE`. I expected the `COMPILER_GYM_CACHE` to not have anything after the experiment exited cleanly.

Is there a way to avoid the experiments leaving the directories behind?

## Steps to reproduce
Running the following on my machine leaves behind about 270 cache directories.

```python
import compiler_gym
import compiler_gym.wrappers
from ray import tune
from ray.rllib.agents.ppo import PPOTrainer


def make_env(env_config):
    env = compiler_gym.make(env_config['cgym_id'])
    env = compiler_gym.wrappers.TimeLimit(env, env_config['timelimit'])
    dataset = env.datasets[env_config['dataset']]
    env = compiler_gym.wrappers.CycleOverBenchmarks(
        env, dataset.benchmarks())
    return env


config = {
    "env_config": {
        "cgym_id": "llvm-autophase-ic-v0",
        "timelimit": 45,
        "dataset": "benchmark://cbench-v1",
    },
    "env": "CompilerGym",
}

stop = {
    "timesteps_total": 10_000,
}

tune.register_env("CompilerGym", make_env)
tune.run(
    PPOTrainer,
    config=config,
    stop=stop,
    name='cgym_cache_dir_demo',
)
```

## Environment

Please fill in this checklist:

- CompilerGym: 0.2.2
- How you installed CompilerGym (conda, pip, source): pip
- OS: Ubuntu 20.04.1 LTS (x86_64)
- Python version: 3.9.7
- Build command you used (if compiling from source): N/A
- GCC/clang version (if compiling from source): N/A
- Bazel version (if compiling from source): N/A
- Versions of any other relevant libraries: ray: 1.10.0, gym: 0.20.0

### PR DESCRIPTION
**Pull request by ChrisCummins**
Summary of changes:

1. Changes the signature of `createAndRunCompilerGymService()` from `[[noreturn]] void` to `[[nodiscard]] int`. This removes the calls to `exit()` from inside the body of the function, allowing runtime services to insert cleanup code after the service has shut down. This is a temporary workaround until #591 is implemented.
2. Adds an explicit call to `BenchmarkFactory::close()` on the global singleton, since otherwise it may not be called. Fixes #582.
3. Ensures that multiple calls to `BenchmarkFactory::close()` are safe.
4. Adds a couple of extra debug logging statements.

### CODE REVIEW

**Comment by mostafaelhoushi** [comment]
Side note: I `build-linux` and `build-macos` are failing this PR and my PR as well... is this a known issue?

File: compiler_gym/service/runtime/CreateAndRunCompilerGymServiceImpl.h [hunk 1]
```diff
@@ -51,7 +51,7 @@ void setGrpcChannelOptions(grpc::ServerBuilder& builder);
 //       createAndRunCompilerGymServiceImpl(argc, argv, "usage string");
 //     }
 template <typename CompilationSessionType>
-[[noreturn]] void createAndRunCompilerGymServiceImpl(int argc, char** argv, const char* usage) {
+[[nodiscard]] int createAndRunCompilerGymServiceImpl(int argc, char** argv, const char* usage) {
```
Comment (mostafaelhoushi) [inline compiler_gym/service/runtime/CreateAndRunCompilerGymServiceImpl.h:54]: out of curiousity, what does `[[nodiscard]]` do?

**Review by mostafaelhoushi — APPROVED** [review]
LGTM

**Comment by ChrisCummins** [comment]
Thanks for the quick review @mostafaelhoushi!

> Side note: I `build-linux` and `build-macos` are failing this PR and my PR as well... is this a known issue?

Yep, everything is on fire #590

File: compiler_gym/service/runtime/CreateAndRunCompilerGymServiceImpl.h (hunk 1 above)
Comment (ChrisCummins) [reply compiler_gym/service/runtime/CreateAndRunCompilerGymServiceImpl.h:54]: It triggers a compiler warning if the user doesn't do anything with the return value. With `-Werror`, it prevents the common typo:
 
```c++
int main(int argc, char** argv) {
  createAndRunCompilerGymServiceImpl(&argc, &argv, usage);
}
```
instead of:

```c++
int main(int argc, char** argv) {
  return createAndRunCompilerGymServiceImpl(&argc, &argv, usage);
}
```
